kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: gitlab-pv-claim
  namespace: default
  labels:
    k8s-app: gitlab-api
    project: gitlab
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi